name: Simple CI for My Website

on:
  push:               
    branches:
      - main          

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List project files
        run: ls -la

      - name: CI confirmation
        run: echo "workflow successfully!!!!done"
